Pace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('student/', include("student.urls"), name="student"),
    path('community/', include("community.urls"), name="community"),
    path('resources/', include("resources.urls"), name="resources"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/urls.py
from django.urls import path
from .import views

app_name = 'community'
urlpatterns = [
    path("", views.home, name="home"),
    path("<int:pk>/post/", views.view_post, name="view_post"),
    path("addPost/", views.add_post, name="add_post"),
    path("searchPost/", views.search_post, name="search_post"),

]

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
urlpatterns = [
    path("", views.home, name="home"),
    path('login/', views.loginPage, name="login"),
    path('register/', views.registerPage, name="register"),
    path('logout/', views.logoutUser, name="logout"),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="home/reset_password.html"),
         name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="home/password_reset_done.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="home/password_reset_confirm.html"),
         name="password_reset_confirm"),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="home/password_reset_complete.html"), name="password_reset_complete"),
]

resources/urls.py
from django.urls import path
from django.views.static import serve
from django.conf import settings
from django.conf.urls import url

from .import views
app_name = 'resources'
urlpatterns = [
    path("", views.home, name="home"),
    url(r'^download/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group

# Create your views here.
from .models import *
from .forms import CreateUserForm


def home(request):
    return render(request, "home/home.html")


def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + username)
            login(request, user)
            return redirect('home')
    context = {'form': form}
    return render(request, 'home/register.html', context)


def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username OR password is incorrect')

    context = {}
    return render(request, 'home/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('login')

home/templates/home/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <title>Pace</title>
    <style>
        @import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css");

        .hero {
            background: linear-gradient(to right, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.1)),
                url("./static/images/c11.jpg");
            height: 100vh;
            background-position: center;
            background-size: cover;
            padding: 0.5rem calc((100vw - 1200px) / 2);
            display: flex;
            justify-content: flex-start;
            align-items: center;
        }

        .hero__content {
            color: white;
            padding: 3rem 1rem;
            line-height: 1;
        }

        .hero__content h1 {
            font-size: clamp(3rem, 8vw, 7rem);
            text-transform: uppercase;
            margin-bottom: 0.8rem;
        }

        .hero__content p {
            font-size: clamp(1rem, 4vw, 2.5rem);
            margin-bottom: 2rem;
        }

        .button {
            padding: 1rem 3rem;
            border: none;
            background: red;
            color: white;
            font-size: 1.2rem;
            outline: none;
            text-decoration: none;
            cursor: pointer;
            transition: 0.3s ease;
            border-radius: 4px;
        }

        .button:hover {
            background: black;
            color: white;
        }

        table {
            font-family: Verdana, Geneva, Tahoma, sans-serif;
            border-collapse: collapse;
            text-align: center;
            position: relative;
            top: 50%;
            left: 50%;
            transform: translate(-50%, 0%);
            width: 800px;
            height: 200px;
            border-radius: 5px 5px 0 0;
        }

        tr {
            transition: all 0.2s ease-in-out;
            cursor: pointer;
        }

        tr:hover,
        tr:focus {
            transform: scaleY(1.02);
            box-shadow: 2px 2px 12px rgba(0, 0, 0, 0.2), -1px -1px 8px rgba(0, 0, 0, 0.2);
        }

        table td,
        table th {
            border: 1px solid #cccccc;
            padding: 10px 12px;
        }

        table th {
            font-weight: bold;
            background-color: #1fb3d3;
            color: #fff;
            text-transform: uppercase;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        tr:last-child {
            border-bottom: 2px solid #1fb3d3;
        }

        @media only screen and (max-width: 870px) {
            table {
                width: 100%;
            }
        }
    </style>
</head>

<body>

    {% include 'home/navbar.html' %}

    {% block content %}

    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.2/dist/chart.min.js" charset="utf-8"></script>

    {% block script %}

    {% endblock script %}



</body>

</html>

home/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<div class="hero">
    <div class="hero__content">
        <h1 class="">Pace Academy</h1>
        <p class="">Where Success Originates</p>
        <a href="{% url 'student' %}" class="button">Get Started</a>
    </div>
</div>
{% endblock content %}

home/templates/home/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            /* background: #7abecc !important; */
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;

        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>

</head>

<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">


                    <h3 id="form-title">LOGIN</h3>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name="username" placeholder="Username..." class="form-control">
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" name="password" placeholder="Password..." class="form-control">
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Login">
                        </div>
                    </form>

                </div>

                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
                    </div>
                    <div class="d-flex justify-content-center links">
                        Forgot Password? <a href="{% url 'reset_password' %}" class="ml-2">Reset Password</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>

</html>

home/templates/home/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Pace</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">Ranklist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'community:home' %}">Community</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'resources:home' %}">Downloads</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="http://127.0.0.1:8000/admin/">Admin Pannel</a>
                </li>

                {% block navitem %}

                {% endblock navitem %}


            </ul>

            {% if user.is_authenticated %}
            <form class="d-flex  me-2">
                <p class="text-white m-2">Hello , {{user.username}}</p>
                <a class="btn btn-outline-primary text-white" href="{% url 'logout' %}">Logout</a>
            </form>
            {% else %}

            <form class="d-flex me-2">
                <a class="btn btn-outline-primary text-white" href="{% url 'login' %}">Login</a>
            </form>
            {% endif %}

        </div>
    </div>
</nav>

home/templates/home/password_reset_complete.html
{% extends 'home/base.html' %}

{% block content %}

<div class="container mt-3">
    <div class="row" style="justify-content: center; align-items: center;">
        <div class="col-md-8">
            <h4 class="text-center alert alert-info">Password Reset Complete</h4>
            <div class="card card-body">
                <p class="m-2 p-2">Your password has been set . You may go ahead and Log in now</p>
                <div>
                    <a href="{% url 'login' %}" class="btn btn-outline-primary m-2">Log In</a>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

home/templates/home/password_reset_confirm.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-3">
    <div class="row" style="justify-content: center; align-items: center;">
        <div class="col-md-8">
            <h4 class="text-center alert alert-info">Password Reset</h4>
            <p class="m-2 p-2">Please enter your new password</p>
            <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <input class="btn btn-primary mt-2" type="submit" value="Send">
            </form>
        </div>
    </div>
</div>

{% endblock content %}

home/templates/home/password_reset_done.html
{% extends 'home/base.html' %}

{% block content %}

<div class="container mt-3">
    <div class="row" style="justify-content: center; align-items: center;">
        <div class="col-md-8">
            <h4 class="text-center alert alert-info">Password Reset Sent</h4>
            <div class="card card-body">
                <p class="m-2 p-2">We have emaild your instruction for setting your password , if an account with email
                    you enterd
                    exists , You should recieve them shortly</p>
                <p class="m-2 p-2">If you don't recieve an email, please make sure you've entered the address you
                    registered with , and check your spam folder</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

home/templates/home/register.html
<!DOCTYPE html>
<html>

<head>
    <title>Sign Up</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            /* background: #7abecc !important; */
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;
        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }
    </style>

</head>

<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            {% for message in messages %}
            <p id="messages" class="text-info text-white">{{message}}</p>
            {% endfor %}
            <div class="user_card">
                <div class="d-flex justify-content-center">
                    <h3 id="form-title">REGISTER ACCOUNT</h3>
                </div>
                <div class="d-flex justify-content-center form_container">

                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            {{form.username}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                            </div>
                            {{form.email}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password1}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password2}}
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Register Account">
                        </div>
                    </form>
                </div>





                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field 
*/

        //Query All input fields
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder = 'Username..';
        form_fields[2].placeholder = 'Email..';
        form_fields[3].placeholder = 'Enter password...';
        form_fields[4].placeholder = 'Re-enter Password...';


        for (var field in form_fields) {
            form_fields[field].className += ' form-control'
        }
    </script>
</body>

</html>

home/templates/home/reset_password.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-3">
    <div class="row" style="justify-content: center; align-items: center;">
        <div class="col-md-8">
            <h4 class="text-center alert alert-info">Password Reset</h4>
            <p>Forgotten your password ? Enter your email address below and we'll email instructions for setting new
                password</p>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.|crispy}}
                <input class="btn btn-primary mt-2" type="submit" value="Send">
            </form>
        </div>
    </div>
</div>


{% endblock content %}