Pace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('student/', include("student.urls"), name="student"),
    path('community/', include("community.urls"), name="community"),
    path('resources/', include("resources.urls"), name="resources"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/urls.py
from django.urls import path
from .import views

app_name = 'community'
urlpatterns = [
    path("", views.home, name="home"),
    path("<int:pk>/post/", views.view_post, name="view_post"),
    path("addPost/", views.add_post, name="add_post"),
    path("searchPost/", views.search_post, name="search_post"),

]

community/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from student.models import Student
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField(max_length=2000)
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(
        upload_to="post", blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'


class Comment(models.Model):
    comment = models.TextField(max_length=2000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    thumb = models.ImageField(
        upload_to="comment", blank=True, null=True)
    timestamp = models.DateTimeField(default=now)

    def __str__(self):
        return self.comment

community/forms.py
from django import forms
from .models import Post, Comment


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'thumb']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.TextInput(attrs={'class': 'form-control'}),
            'thumb': forms.FileInput(attrs={'class': 'form-control'}),
        }


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment', 'thumb']
        widgets = {
            'comment': forms.TextInput(attrs={'class': 'form-control'}),
            'thumb': forms.FileInput(attrs={'class': 'form-control'}),
        }

community/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from .models import Post, Comment
from .forms import AddPostForm, AddCommentForm
# Create your views here.


def home(request):
    allPosts = Post.objects.all().order_by('-date')
    context = {'allPosts': allPosts}
    return render(request, "community/community.html", context)


def view_post(request, pk):
    post = Post.objects.get(id=pk)
    comments = Comment.objects.filter(post=post).order_by('-timestamp')

    if request.method == 'POST':
        form = AddCommentForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user = request.user
            form.instance.post = post
            form.save()
            form = AddCommentForm()
    else:
        form = AddCommentForm()
    context = {'post': post, 'comments': comments, 'form': form}
    return render(request, "community/post.html", context)


def add_post(request):
    if request.method == 'POST':
        form = AddPostForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
        return redirect('community:home')
    else:
        form = AddPostForm()
    context = {'form': form}
    return render(request, 'community/addPost.html', context)


def add_comment(request):
    if request.method == 'POST':
        form = AddCommentForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
        return redirect('community:home')
    else:
        form = AddCommentForm()
    context = {'form': form}
    return render(request, 'community/post.html', context)


def search_post(request):
    query = request.GET.get('search')
    results = Post.objects.filter(
        Q(title__icontains=query) | Q(body__icontains=query)).order_by('-date')

    context = {'results': results, 'query': query}
    return render(request, 'community/search.html', context)

community/templates/community/addPost.html
{% extends 'home/base.html' %}

{% load static %}


{% block content %}
<div class="container mt-3">
    <div class="row" style="justify-content: center; align-items: center;">
        <div class="col-md-8">
            <h4 class="text-center alert alert-info">Add new Post</h4>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primary" type="submit" value="Add">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

community/templates/community/community.html
{% extends 'home/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<div class="container ">
    <div class="row mt-2 d-flex">
        <a href="{% url 'community:add_post' %}"><button class="btn btn-outline-primary" type="submit">Add
                Post</button></a>
        <form class="d-flex mt-2 col-md-6 " method="GET" action="{% url 'community:search_post' %}"
            style="justify-content: space-between;">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search"
                id="search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
    <hr>


    <h2 class="text-center">Recent Posts</h2>
    <div class="row" style="justify-content: center; align-items: center;">

        {% for post in allPosts %}
        <div class="col-10 d-lg-block card m-3">
            <div class="p-4 d-flex flex-column position-static card-body">
                <div class="d-inline-block ">

                    {% if post.author.is_staff %}
                    <img src="{% static 'images/tea.jpg' %}" alt=""
                        style="width: 45px; height: 45px; border-radius: 50%;" class="me-2">
                    <strong class="d-inline-block mb-2 ms-2 text-primary">{{post.author}}</strong>
                    {% else %}
                    <img src="{{post.author.student.image.url}}" alt=""
                        style="width: 45px; height: 45px; border-radius: 50%;" class="me-2">
                    <strong class="d-inline-block mb-2 ms-2 text-primary">{{post.author.student.name}}</strong>
                    {% endif %}
                    <span class="mb-1 ms-2 text-muted">{{post.date | naturaltime}}</span>
                </div>

                <h3 class="mb-0 mt-2">{{post.title}}</h3>
                <p class="card-text mb-auto mt-2">{{post.snippet}}</p>
            </div>

            {% if post.thumb %}

            <img class="bd-placeholder-img w-100 mb-3" height="350" src="{{post.thumb.url}}">
            {% endif %}



            <div class="m-2 p-2">
                <a href="{% url 'community:view_post' post.id %}"><button class="btn btn-outline-primary btn-sm">Add
                        Answer</button></a>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

{% endblock content %}

community/templates/community/post.html
{% extends 'home/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<div class="container my-3">
    <div class="row" style="justify-content: center; align-items: center;">
        <div class="col-10 d-lg-block card m-3">
            <div class="p-4 d-flex flex-column position-static card-body">
                <div class="d-inline-block ">

                    {% if post.author.is_staff %}
                    <img src="{% static 'images/tea.jpg' %}" alt=""
                        style="width: 45px; height: 45px; border-radius: 50%;" class="me-2">
                    <strong class="d-inline-block mb-2 ms-2 text-primary">{{post.author}}</strong>
                    {% else %}
                    <img src="{{post.author.student.image.url}}" alt=""
                        style="width: 45px; height: 45px; border-radius: 50%;" class="me-2">
                    <strong class="d-inline-block mb-2 ms-2 text-primary">{{post.author.student.name}}</strong>
                    {% endif %}
                    <span class="mb-1 ms-2 text-muted">{{post.date | naturaltime}}</span>
                </div>

                <h3 class="mb-0 mt-2">{{post.title}}</h3>
                <p class="card-text mb-auto mt-2">{{post.body}}</p>
            </div>
            <img class="bd-placeholder-img w-100 mb-3" height="350" src="{{post.thumb.url}}">
            <div class="container">
                <h2> Comments ({{comments.count}})</h2>

                {% if user.is_authenticated %}

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input class="btn btn-primary" type="submit" value="Add">
                </form>
                {% else %}
                <h3>Please Login to Comment </h3>
                {% endif %}


                {% for comment in comments %}
                <div class="row my-3">
                    <div class="col-md-1  ">

                        {% if comment.user.is_staff %}
                        <img src="{% static 'images/tea.jpg' %}" alt=""
                            style="width: 45px; height: 45px; border-radius: 50%;" class="me-2">
                        {% else %}
                        <img src="{{comment.user.student.image.url}}" alt=""
                            style="width: 45px; height: 45px; border-radius: 50%;" class="me-2">
                        {% endif %}

                    </div>
                    <div class="col-md-11">

                        {% if comment.user.is_staff %}
                        <b> {{comment.user}}</b>

                        {% else %}
                        <b> {{comment.user.student.name}}</b>
                        {% endif %}

                        {{comment.timestamp | naturaltime}}
                        <div> {{comment.comment}}</div>

                        {% if comment.thumb %}

                        <img class="bd-placeholder-img w-100 mb-3 mt-2" height="350" src="{{comment.thumb.url}}">
                        {% endif %}

                    </div>
                </div>
                <hr>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock content %}

community/templates/community/search.html
{% extends 'home/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<div class="container my-3">
    <div class="row" style="justify-content: center; align-items: center;">
        <h3>Search results for "{{ query }}" : </h3>
        <hr>
        {% for post in results %}
        <div class="col-10 d-lg-block card m-3">
            <div class="p-4 d-flex flex-column position-static card-body">
                <div class="d-inline-block ">

                    {% if post.author.is_staff %}
                    <img src="{% static 'images/tea.jpg' %}" alt=""
                        style="width: 45px; height: 45px; border-radius: 50%;" class="me-2">
                    <strong class="d-inline-block mb-2 ms-2 text-primary">{{post.author}}</strong>
                    {% else %}
                    <img src="{{post.author.student.image.url}}" alt=""
                        style="width: 45px; height: 45px; border-radius: 50%;" class="me-2">
                    <strong class="d-inline-block mb-2 ms-2 text-primary">{{post.author.student.name}}</strong>
                    {% endif %}
                    <span class="mb-1 ms-2 text-muted">{{post.date | naturaltime}}</span>
                </div>

                <h3 class="mb-0 mt-2">{{post.title}}</h3>
                <p class="card-text mb-auto mt-2">{{post.snippet}}</p>
            </div>
            <img class="bd-placeholder-img w-100 mb-3" height="350" src="{{post.thumb.url}}">


            <div class="m-2 p-2">
                <a href="{% url 'community:view_post' post.id %}"><button class="btn btn-outline-primary btn-sm">Add
                        Answer</button></a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}